---
- name: Set up bastion instance
  hosts: bastion
  remote_user: ec2-user
  vars_files:
    - ./tf_variables.yaml
  tasks:
    - name: Add known hosts
      ansible.builtin.copy:
        src: '{{ playbook_dir }}/webserver_key'
        dest: /home/ec2-user/webserver_key
        mode: "0600"

    - name: Copy known_hosts file containing webserver public keys
      ansible.builtin.copy:
        src: '{{ playbook_dir }}/known_hosts.txt'
        dest: /home/ec2-user/.ssh/known_hosts
        mode: "0600"

    - name: Configure mysql database schema
      block:
        - name: Update or install mariadb
          become: true
          ansible.builtin.package:
            name: mariadb105-server.x86_64

        - name: Move script file
          ansible.builtin.copy:
            src: '{{ playbook_dir }}/user.sql'
            dest: /home/ec2-user/user.sql
            mode: "0644"

        - name: Run mysql command
          become: true
          ansible.builtin.shell: mariadb --host={{ db_url }} --port=3306 --user={{ db_user }} --password={{ db_password }} < /home/ec2-user/user.sql
          changed_when: true # temporary hack

- name: Set up web servers
  hosts: webservers
  remote_user: ec2-user # for simplicity

  vars:
    docker_image: mydockertestacc/main:6ff96326
  vars_files:
    - ./tf_variables.yaml

  tasks:
    - name: Update or install docker
      become: true
      ansible.builtin.package:
        name: docker

    - name: Start and enable docker daemon
      become: true
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Pull docker image
      become: true
      community.docker.docker_image:
        name: '{{ docker_image }}'
        source: pull
        pull:
          platform: amd64

    - name: Run docker image
      become: true
      community.docker.docker_container:
        name: webserver_container
        image: '{{ docker_image }}'
        state: started
        published_ports:
          - 80:8080
          - 8088:8088
        env:
          RUN_PROFILE: mysql
          MYSQL_URL: "jdbc:mysql://{{ db_url }}/petclinic"
          MYSQL_USER: '{{ db_user }}'
          MYSQL_PASS: '{{ db_password }}'
