---
- name: Set up web servers
  hosts: webservers
  remote_user: ec2-user # for simplicity

  vars:
    docker_image: mydockertestacc/main:1946d63e
  # vars_files:
  #   - ./tf_variables.yaml

  tasks:
    - name: Update or install docker
      become: true
      ansible.builtin.package:
        name: docker

    - name: Start and enable docker daemon
      become: true
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Pull docker image
      become: true
      community.docker.docker_image:
        name: '{{ docker_image }}'
        source: pull
        pull:
          platform: amd64

    - name: Run docker image
      become: true
      community.docker.docker_container:
        name: 'webserver_container'
        image: '{{ docker_image }}'
        state: started
        published_ports:
          - 80:8080
          - 8088:8088
