locals {
  # Turns a list of ips into a string of ips separated by newlines
  newline_separated_hosts = join("\n", var.webserver_ips)
}

resource "local_file" "tf_ansible_inventory" {
  filename = "${var.ansible_dir}/inventory"
  content  = <<EOF
# Generated by Terraform
# Ansible inventory containing hosts provided by Terraform
[webservers]
${local.newline_separated_hosts}
EOF
}

resource "local_file" "tf_ansible_vars" {
  filename = "${var.ansible_dir}/tf_variables.yaml"
  content  = <<EOF
# Generated by terraform
# Variables describing infrastructure provided with Terraform
---
pubkey_location: ${var.pubkey_path}
EOF
}
