locals {
  newline_separated_hosts = join("\n", var.webserver_ips)
}

resource "local_file" "tf_ansible_inventory" {
  filename = "${var.ansible_dir}/inventory"
  content  = <<EOF
# Ansible inventory generated by Terraform resource
[webservers]
${local.newline_separated_hosts}
EOF
}
